// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import { Modal } from "tailwindcss-stimulus-components";
application.register("modal", Modal)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

