# Dockerfile.dev
FROM ruby:3.2.4

WORKDIR /myapp

RUN apt-get update -qq && apt-get install -y \
  build-essential libpq-dev nodejs yarn \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"]