# Dockerfile.dev
FROM ruby:3.2.4

WORKDIR /myapp

RUN apt-get update -qq && apt-get install -y \
  build-essential libpq-dev nodejs yarn \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

ENV RAILS_ENV=development
ENV RAILS_SERVE_STATIC_FILES=true
ENV RAILS_LOG_TO_STDOUT=true

CMD ["rails", "server", "-b", "0.0.0.0"]
