version: '3'
services:
  postgresdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:   
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rails:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      DATABASE_HOST: postgresdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: ruby_dev_test_1_development

volumes:
  postgres_data:
