apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
        - name: {{ .Chart.Name }}-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: RAILS_ENV
              value: {{ .Values.env.RAILS_ENV | quote }}
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretEnv.RAILS_MASTER_KEY.secretName }}
                  key: {{ .Values.secretEnv.RAILS_MASTER_KEY.key }}
            - name: RUBY_DEV_TEST_1_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_HOST.secretName }}
                  key: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_HOST.key }}
            - name: RUBY_DEV_TEST_1_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_PASSWORD.secretName }}
                  key: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_PASSWORD.key }}
            - name: RUBY_DEV_TEST_1_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_USERNAME.secretName }}
                  key: {{ .Values.secretEnv.RUBY_DEV_TEST_1_DATABASE_USERNAME.key }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretEnv.SECRET_KEY_BASE.secretName }}
                  key: {{ .Values.secretEnv.SECRET_KEY_BASE.key }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapRef }}
