name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Install system dependencies (ImageMagick)
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick libvips
      - name: Set up pgcrypto extension
        run: |
          psql postgres://rails:password@localhost:5432/db_test -c 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";'
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
          cache: "yarn"
      - name: Run bundles JS & CSS
        run: |
          yarn install
          yarn build
          yarn build:css
      - name: Run tests
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop